<a href="https://colab.research.google.com/github/z4sdream/test1/blob/main/python_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **파이썬 프로그래밍 기말고사**

기말 고사 유의 사항

1. 문제의 답안을 함수로 작성하되, 반드시 함수 이름은 문제에서 제시하는 함수명으로 할것 (함수명이 다르면 점수 획득 불가능)
1. 각 문제의 답안은 답안 작성 셀에서 작성할 것
1. 모든 문제는 함수의 매개변수 입력을 통해 데이터를 전달 받고, 결과를 반환하는 함수를 정의하는 것임 (주의: input()는 키보드 입력이며, 함수 입력이 아님, print()는 모니터에 출력하는 함수이며, 함수 반환이 아님)
1. 함수의 입력과 반환 시 데이터 타입도 반드시 지킬것 (예: 문자열 반환이라는 문제에서는 반드시 문자열을 반환 해야함)
1. 답안 제출은 함수가 정의된 부분만 제출하고, 나머지 코드는 지우고 제출할 것, 답안 제출시 input() 함수나 , print() 함수가 있으면 안됨
1. 코드 작성이 끝난 파일은 개별적으로 함수를 호출해서 검수를 거쳐 정답이 맞는지 확인할 것
1. 작성된 답안은 colab의 상단 메뉴의 파일--> 다운로드 --> .py 로 다운 받아 학교 LMS 에 제출할 것  ( .py 다운로드시 경고창이 뜨지만, 계속 버튼을 눌러 다운 할것)
1. .py 가 학교 LMS 에 올라가지 않을경우 ZIP으로 압축하여 업로드 가능
1. 파일의 이름은 자신의 학번.py      예) 학번이 2021111000 일 경우,     2021111000.py 파일을 제출
1. 코드는 자동 채점이 되며, 각 문제당 부분 점수는 없음
1. 시험지 및 답안을 절대 유출 금지(타인 및 개인 블로그 포함)하며, 유출될 경우 불이익을 감수할 것
1. 제출 기한을 넘겨 답안을 제출하는 것은 불가

## 문제 1) - 5점


<strong>* 하나의 정수를 함수의 입력으로 받아, 이 정수가 홀수 인지 짝수 인지를 판별하여 짝수이면 "짝", 홀수 이면 "홀"이라는 문자열을 반환하는 함수를 작성하시오</strong>


* 예1) 
 * 입력(정수) : 2 <br>
 * 반환(문자열) : "짝"

 * 함수 입력 
    ```
    exam1(2)

    ```
 * 함수 반환
    ```
    "짝"

    ```



* 예2)
 * 입력(정수): 3 <br>
 * 반환(문자열): "홀"

 * 함수 입력
    ```
    exam1(3)
    ```
 * 함수 반환
    ```
    "홀"

    ```



* 함수 이름: exam1<br>      (반드시 함수 이름을 exam1로 작성할것!!)

* 함수 작성 힌트 <br>



```
def exam1(a):
    b = a가 짝수라면 "짝"이라는 문자열을 대입
    return b
```

In [ ]:
###### 1번 문제 답안 작성 셀 ######

## 문제 2) - 10점

<strong> * 하나의 리스트를 함수의 입력으로 넣으면, 리스트안의 중복을 제거한 다음 중복 제거된 리스트를 반환하는 함수를 작성하시오. (단, 데이터 순서를 유지할 것)</strong>

* 예1) 
   * 입력(리스트) : [1,2,1,1,1] <br>
   * 반환(리스트) : [1,2]

   * 함수 입력 
       ```
       exam2([1,2,1,1,1])

       ```
   * 함수 반환
       ```
       [1,2]

       ```

* 예2)

 * 입력(리스트): [3,3,4,5] <br>
 * 반환(리스트): [3,4,5]

 * 함수 입력 
    ```
    exam2([3,3,4,5])

    ```
 * 함수 반환
   ```
   [3,4,5]

   ```



* 함수 이름: exam2 <br>      (반드시 함수 이름을 exam2로 작성할것!!)

* 함수 작성 가이드 <br>



```
def exam2(a):
    b = a리스트의 중복제거한 리스트
    return b
```

In [ ]:
###### 2번 문제 답안 작성 셀 ######

## 문제 3) - 10점

<strong> 2부터 9까지의 정수중 하나를 함수의 입력으로 넣으면, 구구단의 결과를 리스트로 반환하는 함수를 작성하시오</strong> 

* 예1)

  * 입력(정수) : 2
  * 반환(리스트) : [2,4,6,8,10,12,14,16,18]

  * 함수 입력 
    ```   
    exam3(2)
    ```
  * 함수 반환
    ```
    [2,4,6,8,10,12,14,16,18]
    ```

* 예2)

  * 입력(정수): 3
  * 반환(리스트): [3,6,9,12,15,18,21,24,27]


  * 함수 입력 
    ```
    exam3(3)
    ```

  * 함수 반환
    ```
    [3,6,9,12,15,18,21,24,27]
    ```

* 함수 이름: exam3
(반드시 함수 이름을 exam3로 작성할것!!)

* 함수 작성 힌트



```
def exam3(a):
    b = a단에 대한 구구단 결과 리스트
    return b
```

In [ ]:
###### 3번 문제 답안 작성 셀 ######

## 문제 4) - 10점

<strong>다음 데이터를 함수 내에 딕셔너리 형태로 저장한 다음, 함수의 입력으로 딕셔너리의 키에 해당하는 문자열을 받으면, 키에 해당하는 값을 반환하는 함수를 작성하시오. </strong>

(함수내 저장해야하는 데이터, 반드시 함수내에 데이터를 저장할 것)

```
phones = {"S5": 2014, "S7": 2016, "note8": 2017, "S9": 2018, "S10": 2019}
```

* 예1)<br>

    * 입력(문자열) : "S5"<br>
    * 반환(정수) : 2014<br>

    * 함수 입력 
        ```
        exam4("S5")

        ```

    * 함수 반환

        ```
        2014

        ```

* 예2)<br>

    * 입력(문자열) : "S7"<br>
    * 반환(정수) : 2016<br>

    * 함수 입력 
        ```
        exam4("S7")

        ```
    
    * 함수 반환
        ```
        2016
        ```


* 함수 이름: exam4  <br>
(반드시 함수 이름을 exam4로 작성할것!!)<br>

* 함수 작성 가이드

```
def exam4(a):
    b = a의 키(key)값에 해당하는 값(value)
    return b
```

In [ ]:
###### 4번 문제 답안 작성 셀 ######

## 문제5) - 5점

<strong>주민등록번호 13자리 문자열을 함수의 입력으로 받아, 해당 주민번호가 남성인지 여성인지를 판별하여 반환하는 함수를 작성하시오. </strong><br>

입력 문자열은 "주민번호 앞자리 - 뒷자리"로 구성됨<br>
반환 문자열은 "남성", "여성" 둘중 하나<br>
<br>

주민번호 뒷자리중 첫번째 숫자가 1이면 남성, 2이면 여성

* 예1)<br>

  * 입력(문자열) : "820327-1022421"<br>
  * 반환(문자열) : "남성"<br>

  * 함수 입력 
      ```
      exam5("820327-1022421")
    
      ```
  * 함수 반환 
    
     ```
    "남성"
     ```
<br>

* 예2)

  * 입력(문자열) : "820327-2022421"<br>
  * 반환(문자열) : "여성"<br>
  * 함수 입력 
      ```
      exam5("820327-2022421")

      ```

  * 함수 반환

      ```
      "여성"
      ```




* 함수 이름: exam5
(반드시 함수 이름을 exam5로 작성할것!!)

* 함수 작성 가이드


```

def exam5(a):
    b = a 주민번호를 판별후 "남성", "여성" 이라는 문자열 둘 중 하나를 대입 
    return b
```

In [ ]:
###### 5번 문제 답안 작성 셀 ######

## 문제 6) - 5점

<strong>하나의 리스트를 함수의 입력으로 받아, 이 리스트에서 짝수 데이터를 제거한 리스트를 반환하시오. (기존 리스트 순서는 그대로 유지)</strong><br>



* 예1)<br>

  * 입력(리스트) : [1, 2, 3, 4, 5, 6]<br>
  * 반환(리스트) : [1, 3, 5]<br>

  * 함수 입력 
      ```
      exam6([1, 2, 3, 4, 5, 6])
    
      ```
  * 함수 반환 
    
     ```
     [1, 3, 5]
     ```

* 예2)

    * 입력(리스트) : [9, 10, 11, 13, 18, 20]<br>
    * 반환(리스트) : [9, 11, 13]<br>

    * 함수 입력 
        ```
        exam6([9, 10, 11, 13, 18, 20])
        
        ```
    * 함수 반환 
        
        ```
        [9, 11, 13]
        ```


* 함수 이름: exam6
(반드시 함수 이름을 exam6로 작성할것!!)

* 함수 작성 힌트


```

def exam6(a):
    b = a 리스트에서 짝수 데이터를 제거한 리스트
    return b
```

In [ ]:
###### 6번 문제 답안 작성 셀 ######

## 문제 7) - 15점


<strong>하나의 문자열을 함수의 입력으로 받아, 이 문자열이 오직 '0'과 '1'로 만 이루어진 문자열이면 True를 반환하고, 그외 다른 문자열이 포함되어 있을 경우 False를 반환하는 함수를 작성하시오. </strong><br>



* 예1)<br>

  * 입력(문자열) : "101010101010"<br>
  * 반환(불) : True<br>
  
  * 함수 입력 
      ```
      exam7("101010101010")
    
      ```
  * 함수 반환 
    
     ```
     True
     ```

* 예2)<br>

    * 입력(문자열) : "11A02011"<br>
    * 반환(불) : False<br>

    * 함수 입력 
        ```
        exam7("11A02011")
        
        ```
    * 함수 반환 
        
        ```
        False
        ```

* 함수 이름: exam7
(반드시 함수 이름을 exam7로 작성할것!!)

* 함수 작성 가이드


```

def exam7(a):
    b = a 문자열이 '0'과 '1'로만 되어 있으면 True, 그외 다른 문자를 포함하면 False
    return b
```

In [ ]:
###### 7번 문제 답안 작성 셀 ######

## 문제 8 - 10점

<strong>정수로 구성된 하나의 리스트를 함수의 입력으로 받으면, 리스트 안의 데이터를 모두 절댓값으로 변경한 리스트를 반환 하는 함수를 작성하시오 </strong><br>


* 예1)<br>

  * 입력(리스트) : [1, -2, -3, -5, 8]<br>
  * 반환(리스트) : [1, 2, 3, 5, 8]<br>

  * 함수 입력 
      ```
      exam8([1, -2, -3, -5, 8])
    
      ```
  * 함수 반환 
    
     ```
     [1, 2, 3, 5, 8]
     ```

* 예2)<br>

    * 입력(리스트) : [-2, 3, -4, -5, -7]<br>
    * 반환(리스트) : [2, 3, 4, 5, 7]<br>

    * 함수 입력 
        ```
        exam8([-2, 3, -4, -5, -7])
        
        ```
    * 함수 반환 
        
        ```
        [2, 3, 4, 5, 7]
        ```

* 함수 이름: exam8
(반드시 함수 이름을 exam8로 작성할것!!)

* 함수 작성 가이드


```

def exam8(a):
    b = a의 모든 데이터를 양의 정수로 변경한 리스트
    return b
```

In [ ]:
###### 8번 문제 답안 작성 셀 ######

## 문제 9) - 15점

휴대전화 번호를 문자열 형태로 함수의 매개변수로 입력 받으면, 휴대전화 4개의 뒷자리를 ####으로 바꾸어 반환하는 함수를 작성하시오.



* 예1) <br>

    * 입력(문자열) : "010-3222-1234"<br>
    * 반환(문자열) : "010-3222-####"<br>


    * 함수 입력 
       ```
       exam9("010-3222-1234")
       ```

    * 함수 반환 
        ```
        "010-3222-####"
        ```

* 예2)<br>

    * 입력(문자열) : "010-1221-0984"<br>
    * 반환(문자열) : "010-1221-####"<br>

    * 함수 입력 
        ```
        exam9("010-1221-0984")
            
        ```
    * 함수 반환 
         
        ```
        "010-1221-####"
        ```
 
* 함수 이름: exam9 (반드시 함수 이름을 exam9로 작성할것!!)<br>

함수 작성 가이드

```

def exam9(a):
    b = a 문자열의 뒤의 4개를 ####로 마스킹한 문자열
    return b
```

In [ ]:
###### 9번 문제 답안 작성 셀 ######

## 문제 10) - 15점

<strong> 선거 투표지를 리스트에 담아 놓는 자료가 있다. 이 리스트를 함수의 입력으로 넣으면, 최종 다득표자의 이름을 문자열로 반환하는 함수를 작성하시오. (단, 동점 득표가 없다고 가정한다.) </strong> 



* 예1) <br>

   * 입력(리스트) : ["John", "Joseph", "Joseph", "Joseph", "Peter", "Oliver","Nicholas"] <br>
   * 반환(문자열) : "Joseph" <br>


   * 함수 입력 
      ```
      exam10(["John", "Joseph", "Joseph", "Joseph", "Peter", "Oliver","Nicholas"])
      ```
        
   * 함수 반환 
      ```
      "Joseph"
      ```

* 예2)<br>

    * 입력(리스트) : ["Kim", "Kim", "Park"] <br>
    * 반환(문자열) : "Kim" <br>

    * 함수 입력 
        ```
        exam10(["Kim", "Kim", "Park"])                 
        ```
        
    * 함수 반환 
            
        ```
        "Kim"
        ```



* 함수 이름: exam10 (반드시 함수 이름을 exam10로 작성할것!!)<br>

함수 작성 가이드

```

def exam10(a):
    b = a 리스트에서 가장 많은 문자열
    return b
```

In [ ]:
###### 10번 문제 답안 작성 셀######